/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BaseButton {
        "borderRadius": string;
        "class": string;
        "customStyle": { [key: string]: string };
        "disabled": boolean;
        "handleClick": EventListener;
        "type": string;
    }
    interface BaseCard {
        "class": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBaseButtonElement extends Components.BaseButton, HTMLStencilElement {
    }
    var HTMLBaseButtonElement: {
        prototype: HTMLBaseButtonElement;
        new (): HTMLBaseButtonElement;
    };
    interface HTMLBaseCardElement extends Components.BaseCard, HTMLStencilElement {
    }
    var HTMLBaseCardElement: {
        prototype: HTMLBaseCardElement;
        new (): HTMLBaseCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "base-button": HTMLBaseButtonElement;
        "base-card": HTMLBaseCardElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BaseButton {
        "borderRadius"?: string;
        "class"?: string;
        "customStyle"?: { [key: string]: string };
        "disabled"?: boolean;
        "handleClick"?: EventListener;
        "type"?: string;
    }
    interface BaseCard {
        "class"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "base-button": BaseButton;
        "base-card": BaseCard;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "base-button": LocalJSX.BaseButton & JSXBase.HTMLAttributes<HTMLBaseButtonElement>;
            "base-card": LocalJSX.BaseCard & JSXBase.HTMLAttributes<HTMLBaseCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
